# version: "3"
# services:
#   django:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 8000:8000
#     depends_on:
#       - mysql

#   mysql:
#     image: mysql:latest
#     environment:
#       - MYSQL_ROOT_PASSWORD=''
#       - MYSQL_DATABASE=shoponline
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=''
